### ISSUE TITLE
Toggle bots web indicator

### ISSUE THREAD

**Issue by Kanin** [GriefMoDz/better-status-indicators#1] opened 2020-12-22 01:30 UTC
A setting to toggle the web indicator on bots would be nice :)  ![image](https://kanin.ourmainfra.me/2020/12/22/O3uLrD)

**Comment by GriefMoDz** [comment] 2020-12-22 01:56
Thanks for the suggestion! However, it seems you've either missed or haven't reviewed most of the options available on the settings page; toggling the web status indicator for bots has been an active feature since the initial release (78649a8).

I'll now be closing this issue as it is a duplicate of one of the features already shipped with the plug-in. Cheers!

**Closed by GriefMoDz** 2020-12-22 01:56 UTC
